# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = MenJinManager
DESTDIR = ../bin
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
FORMS += ./ui/CMenJinManager.ui 
UI_DIR += .
RCC_DIR += .
include(MenJinManager.pri)
