# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = MenJinManager
DESTDIR = ../bin
CONFIG += debug
LIBS += -L"../../bin" \
    -l$(Qt_LIBS_) \
    -l/"$(INHERIT)/" \
    -lHCNetSDK
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(MenJinManager.pri)
